FROM ubuntu:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y g++ \
    curl \
    unzip \
    tar \
    git \
    yasm \
    make \
    build-essential \
    gdb \
    libx11-dev \
    libpthread-stubs0-dev \
    bazel